### ISSUE TITLE
SPAN_KIND macros undefined

### ISSUE THREAD

**Issue by ioolkos** [opentelemetry-beam/opentelemetry_zipkin#12]
Should those ?SPAN_KIND macros come from opentelemetry or be local to the Zipkin app? This seems to come from the switch to protobuf.

```
===> Compiling opentelemetry_api
===> Compiling opentelemetry
===> Compiling opentelemetry_zipkin
===> Compiling _build/default/lib/opentelemetry_zipkin/src/opentelemetry_zipkin.erl failed
_build/default/lib/opentelemetry_zipkin/src/opentelemetry_zipkin.erl:131: undefined macro 'SPAN_KIND_UNSPECIFIED'

_build/default/lib/opentelemetry_zipkin/src/opentelemetry_zipkin.erl:74: function to_kind/1 undefined

make: *** [Makefile:26: rel] Error 1
```
I've adapted to the "otel" module names here: https://github.com/ioolkos/opentelemetry_zipkin/commit/cfbbee5f2adfcc1082aa3999bc634dded840fff1, but that's unrelated.
Thanks so much!

**Comment by tsloughter** [comment]
I think `unspecified` was removed in the spec, I'll get a PR up.
