### ISSUE TITLE
Missing dep: inets

### ISSUE THREAD

**Issue by jeanparpaillon** [opentelemetry-beam/opentelemetry_zipkin#7]
opentelemetry_zipkin uses httpc module, from the inets application.
So, inets application should be listed in dependencies for releases.

**Comment by tsloughter** [comment]
@jeanparpaillon yup, thanks. I plan to make the client configurable, but since I haven't yet I'll go ahead and add inets to the .app.src exlicitly. Thanks.

**Comment by tsloughter** [comment]
Done.

**Comment by jeanparpaillon** [comment]
:+1:  thanks
